version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/svelte"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/svelte"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
