syntax = "proto3";

package dionysus.user.v1;

import "dionysus/common/v1/asset.proto";

message UserID {
  uint64 value = 1;
}

enum AgeBracket {
  AGE_BRACKET_UNSPECIFIED = 0;
  AGE_BRACKET_PEGI_3 = 1;
  AGE_BRACKET_PEGI_7 = 2;
  AGE_BRACKET_PEGI_12 = 3;
  AGE_BRACKET_PEGI_16 = 4;
  AGE_BRACKET_PEGI_18 = 5;
}

message User {
  UserID id = 1;
  string username = 2;
  string display_name = 3;
  optional dionysus.common.v1.Asset profile_picture = 4;
  optional AgeBracket age = 5;
}

// message GetFriendListRequest {}

// message GetFriendListResponse {
//   repeated User friends = 1;
// }

// service UserService {
//   rpc GetFriendList(GetFriendListRequest) returns (GetFriendListResponse);
// }
